CREATE TABLE IF NOT EXISTS "user"
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    email text NOT NULL,
    firstname text,
    CONSTRAINT user_id_pk PRIMARY KEY (id),
    CONSTRAINT email_unique UNIQUE (email)
)